src/main/java/com/example/model/Point.java
package com.example.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.GenericGenerator;

import java.sql.Timestamp;
import java.time.format.DateTimeFormatter;

@Entity
@Table (name = "Points")
public class Point {

    @Id
    @GeneratedValue
    private Long id;
    private Double x;
    private Double y;
    private Double r;
    private Boolean hit;
    @Column(nullable = false)
    private Timestamp clickTime;

    public Point(Double x, Double y, Double r){
        this.x = x;
        this.y = y;
        this.r = r;
    }

    public Point(Double x, Double y) {
        this(x, y, 10d);
    }

    public Point() {
    }

    public Double getR() {
        return r;
    }

    public void setR(Double r) {
        this.r = r;
    }

    public Long getId() {
        return id;
    }

    public Double getX() {
        return x;
    }

    public void setX(Double x) {
        this.x = x;
    }

    public Double getY() {
        return y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    public Boolean getHit() {
        return hit;
    }

    public void setHit(Boolean hit) {
        this.hit = hit;
    }

    public Timestamp getClickTime(){ return clickTime; }
    public String getClickTimeString() {
        String timeColonPattern = "HH:mm:ss";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(timeColonPattern);
        return formatter.format(clickTime.toLocalDateTime());
    }

    public void setClickTime(Timestamp clickTime){ this.clickTime = clickTime; }
}

src/main/java/com/example/mbeans/AverageTimeMBean.java
package com.example.mbeans;

public interface AverageTimeMBean {
    long getAverage();
}

src/main/java/com/example/mbeans/CountHitsMBean.java
package com.example.mbeans;

public interface CountHitsMBean {
    long getCount();

    long getMisses();
}

src/main/java/com/example/mbeans/SendInfoMBean.java
package com.example.mbeans;

public interface SendInfoMBean {
    void sendNotification();
}

src/main/java/com/example/view/PointsBean.java
package com.example.view;

import com.example.buisness.CheckPoint;
import com.example.mbeans.AverageTime;
import com.example.mbeans.CountHits;
import com.example.mbeans.SendInfo;
import com.example.model.Point;
import com.example.persistence.PointService;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;

import javax.management.MBeanServer;
import javax.management.ObjectName;
import java.io.Serializable;
import java.lang.management.ManagementFactory;
import java.sql.Timestamp;
import java.util.List;


@Named
@ApplicationScoped
public class PointsBean implements Serializable {

    private double x = 0d;
    private double y = 0d;
    private double r = 3.0d;

    private List<Point> pointsCollection = null;
    private final int offset = 0;

    private final Point pointField = new Point();
    private final Point pointGraphic = new Point();
    private long missed = 0;
    private long shots = 0;
    private final String square = "0";
    private final String message="";

    //=============== DB SERVICE ========================
    private final PointService pointService = PointService.getInstance();

    //================ MBEANS  activation =====================
    private static final AverageTime averageTime = new AverageTime();
    private static final CountHits countHits = new CountHits();
    private static final SendInfo sendInfo = new SendInfo();
//    static {
//        try {
//            MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
//            ObjectName myPersonalBean = new ObjectName("itmo.mispi.lab4:type=AverageTime");
//            ObjectName myPersonalBean2 = new ObjectName("itmo.mispi.lab4:type=CountHits");
//            ObjectName myPersonalBean3 = new ObjectName("itmo.mispi.lab4:type=SendInfo");
//            mbs.registerMBean(averageTime, myPersonalBean);
//            mbs.registerMBean(countHits, myPersonalBean2);
//            mbs.registerMBean(sendInfo, myPersonalBean3);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//    }

    //================== Checker ==============================
    @Inject
    private CheckPoint checkPoint;

    //================== GETTERS & SETTERS ===================

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }

    public double getR() {
        return r;
    }

    public void setR(double r) {
        this.r = r;
    }

    public Point getPointField() {
        return pointField;
    }

    public long getShots() {
        return shots;
    }

    public long getMissed() {
        return missed;
    }

    public String getSquare() {
        return square;
    }

    public String getMessage() {
        return message;
    }

    public int getOffset() {
        return offset;
    }

    public List<Point> getPointsCollection() {
        return pointsCollection;
    }

    public Point getPointGraphic() {
        return pointGraphic;
    }

    //==========================================================
    public void uploadPoints() {
        pointsCollection = pointService.getAllPoints();
        shots = pointService.getRecordsCount();
        missed = pointService.getMissedCount();
    }

    public void submitFieldPoints() {
        try {
            Point point = new Point(x, y, r);

            if (Math.abs(point.getX()) > r || Math.abs(point.getY()) > r)
                sendInfo.sendNotification();

            Timestamp currentTimestamp = new Timestamp(System.currentTimeMillis());
            point.setClickTime(currentTimestamp);
            boolean result = checkPoint.check(point);

            // set point.hit
            point.setHit(result);
            // save the point into DB
            pointService.addPoint(point);
        } catch (NumberFormatException e) {
            // TODO
        }
    }

    public void submitGraphicPoints() {

    }

    public void submitR() {

    }

    public String getDateOffset(int offset, String date) {

        return date;
    }

    public void clear() {
        pointService.truncate();
    }


    private void addPointWithCalculatedResultToDatabase(Point point) {

    }
}

src/main/webapp/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC
        "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        lang="en"
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:a="http://xmlns.jcp.org/jsf/passthrough"

>
<h:head>
    <title>Web3-MBeans</title>
    <link rel="stylesheet" href="./resources/styles/graphic.css"/>
    <link rel="stylesheet" href="./resources/styles/style.css"/>
    <script type="text/javascript" src="./resources/scripts/jquery.js"></script>
</h:head>

<h:body styleClass="h-body">
<!--    <script src="./resources/scripts/clock2.js" type="text/javascript"></script>-->
    <div class="page">
        <div class="graphic">
            <svg xmlns="http://www.w3.org/2000/svg" width="300" height="300">
                <line x1="0" y1="150" x2="300" y2="150" stroke="#000720"></line>
                <line x1="150" y1="0" x2="150" y2="300" stroke="#000720"></line>
                <line x1="270" y1="148" x2="270" y2="152" stroke="#000720"></line>
                <text x="265" y="140">#{pointsBean.r}</text>
                <line x1="210" y1="148" x2="210" y2="152" stroke="#000720"></line>
                <text x="200" y="140">#{pointsBean.r/2}</text> <!--  левая черта -->
                <line x1="90" y1="148" x2="90" y2="152" stroke="#000720"></line>
                <text x="75" y="140">#{-pointsBean.r/2}</text> <!-- правая черта -->
                <line x1="30" y1="148" x2="30" y2="152" stroke="#000720"></line>
                <text x="20" y="140">#{-pointsBean.r}</text> <!-- Крайняя правая черта -->
                <line x1="148" y1="30" x2="152" y2="30" stroke="#000720"></line>
                <text x="156" y="35">#{pointsBean.r}</text>
                <line x1="148" y1="90" x2="152" y2="90" stroke="#000720"></line>
                <text x="156" y="95">#{pointsBean.r/2}</text> <!-- верхняя черта -->
                <line x1="148" y1="210" x2="152" y2="210" stroke="#000720"></line>
                <text x="156" y="215">#{-pointsBean.r/2}</text> <!-- нижняя черта -->
                <line x1="148" y1="270" x2="152" y2="270" stroke="#000720"></line>
                <text x="156" y="275">#{-pointsBean.r}</text> <!-- Самая нижняя черта -->
                <polygon points="300,150 295,155 295, 145" fill="#000720" stroke="#000720"></polygon> <!--Треугольник справа-->
                <polygon points="150,0 145,5 155,5" fill="#000720" stroke="#000720"></polygon> <!-- Треугольник сверху  -->
                <!--RECTANGLE-->
                <rect class="rectangle" x="30" y="150" width="120" height="120"></rect>
                <!--TRIANGLE-->
                <polygon class="triangle" points="210,150 150,210 150,150"></polygon>
                <!--QUARTER-->
                <path class="quarter"
                      d="M 150 30 A 125 125, 90, 0, 0, 30 150 L 150 150 Z"></path>
                <!--DOT-->
                <circle id="pointer" r="5" cx="150" cy="150" fill-opacity="0.7" fill="white" stroke="firebrick"
                        visibility="hidden"></circle>
            </svg>
            <div>
                <p style="color: black">
                    Total shots - #{pointsBean.shots} missed - #{pointsBean.missed}
                </p>
            </div>
        </div>

        <div class="starter">
            <h:link outcome="starter">Go to starter page</h:link>
        </div>

        <div class="card">
            <div class="form">
                <h:form id="form">
                    <div class="x-value">
                        <p style="color: yellow">Choose X:</p>
                        <h:selectOneRadio id="x"
                                          value="#{pointsBean.x}"
                                          required="true"
                                          requiredMessage="X is required">
                            <f:selectItem itemValue="-4" itemLabel="-4"/>
                            <f:selectItem itemValue="-3" itemLabel="-3"/>
                            <f:selectItem itemValue="-2" itemLabel="-2"/>
                            <f:selectItem itemValue="-1" itemLabel="-1"/>
                            <f:selectItem itemValue="0" itemLabel="0"/>
                            <f:selectItem itemValue="1" itemLabel="1"/>
                            <f:selectItem itemValue="2" itemLabel="2"/>
                        </h:selectOneRadio>
                        <h:message for="x" style="color: red"/>
                    </div>

                    <div class="y-value">
                        <p style="color: yellow">Choose Y:</p>

                        <h:inputText styleClass="my-input" style="color: black"
                                     id="y" name="y" value="#{pointsBean.y}"
                                     a:placeholder="Value in [-5..5]"
                                     converterMessage="Y must be number..."
                                     validatorMessage="Y must be number between -5 and 5 inclusive"
                                     required="true" requiredMessage="X is required" maxlength="6"
                                     onkeyup="this.value = this.value.replace(/[^0-9.\-]/g, '')">
                            <f:validateDoubleRange minimum="-5" maximum="5"/>
                        </h:inputText>
                        <h:message for="y" style="color: red"/>
                        <div class="invalid-y d-none h5" style="color: red"></div>
                    </div>

                    <div class="r-value">
                        <p style="color: yellow">Choose R:</p>
                        <h:selectOneRadio id="r"
                                          value="#{pointsBean.r}"
                                          required="true"
                                          requiredMessage="R is required">
                            <f:selectItem itemValue="1" itemLabel="1"/>
                            <f:selectItem itemValue="1.5" itemLabel="1.5"/>
                            <f:selectItem itemValue="2" itemLabel="2"/>
                            <f:selectItem itemValue="2.5" itemLabel="2.5"/>
                            <f:selectItem itemValue="3" itemLabel="3"/>
                        </h:selectOneRadio>
                        <h:message for="r" style="color: red"/>

                        <h:commandButton styleClass="my-button" type="submit" value="Submit"
                                         id="submit-button"
                                         action="#{pointsBean.submitFieldPoints}" >
                        </h:commandButton>

                        <h:commandButton styleClass="my-button" type="submit" value="Clear All"
                                         action="#{pointsBean.clear}">
                        </h:commandButton>
                    </div>

                </h:form>
            </div>


        </div>
        <div class="table">
            <div>Results</div>
            <h:dataTable id="result-table" value="#{pointsBean.pointsCollection}" var="point"
                         columnClasses="column1,column2,column3,column4,column5">
                <f:event type="preRenderView" listener="#{pointsBean.uploadPoints}"/>

                <h:column>
                    <f:facet name="header"  style="color: yellow">X</f:facet>
                    ${point.x}
                </h:column>
                <h:column>
                    <f:facet name="header" style="color: yellow">Y</f:facet>
                    ${point.y}
                </h:column>

                <h:column>
                    <f:facet name="header" style="color: yellow">R</f:facet>
                    ${point.r}
                </h:column>

                <h:column>
                    <f:facet name="header" style="color: yellow">Result</f:facet>
                    ${point.hit ? "Hit" : "None"}
                </h:column>

                <h:column>
                    <f:facet name="header" id="final_time"  style="color: yellow">Click time</f:facet>
                    ${point.clickTimeString}
                </h:column>

            </h:dataTable>
        </div>
    </div>
        <script type="text/javascript" src="./resources/scripts/setPointer.js"></script>
</h:body>

</html>

src/main/webapp/starter.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xml:lang="en"
      lang="en"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
>
<f:view>
    <h:head>
        <title>Web3-MBeans</title>
        <link rel="stylesheet" href="./resources/styles/style.css"/>
    </h:head>

    <h:body>
    <div id="header">
        <span id="variant-info" >Variant 663258</span>
        <span id="student-info">Kupershmidt Lev, P32222</span>
    </div>
    <div class="page">
        <div class="card">
            <div align="center">
                <canvas id="clock" title="clock" width="300px" height="300px" style="padding-top: 25px"/>
            </div>
            <div id="time-container"></div>
            <script src="./resources/scripts/clock.js" type="text/javascript"></script>
            <h:link outcome="main">Go to main page</h:link>
        </div>
    </div>

    </h:body>
</f:view>

</html>